#!/usr/bin/env bash
#asd

sudo apt update
sudo apt -y install nginx
sudo chmod 777 /var/www/html/index.html
echo 'Hello World' | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
