#!/usr/bin/env bash
#comment

sudo apt update
sudo apt -y install nginx

sudo chmod 777 /var/www/html/index.html
echo 'Hello World' > /var/www/html/index.html

sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

sudo touch /var/www/html/error404-page.html
sudo chmod 777 /var/www/html/error404-page.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error404-page.html
sudo sed -i '55i error_page 404 /error404-page.html;' /etc/nginx/sites-enabled/default

sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default

sudo service nginx restart
