#!/usr/bin/env bash
#/g Replace the contents of the pattern space with the contents of the hold space.
#s/regexp/replacement/flags
#The / characters may be uniformly replaced by any other single character within any given s command.

sudo apt update
sudo apt -y install nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
