#!/usr/bin/env bash
#Block incomming traffix except from 22, 443, 80
#https://adamtheautomator.com/ufw-firewall/#:~:text=Installing%20UFW%20and%20Enabling%20IPv6%20Connection,-Even%20though%20UFW&text=Install%20UFW%20first%20with%20the,to%20allow%20connections%20over%20IPv6.&text=1.,update%20for%20less%20user%20intervention.
#https://www.digitalocean.com/community/tutorials/ufw-essentials-common-firewall-rules-and-commands

sudo apt update -y
sudo apt install ufw -y

sudo sed -i "s/IPV6=no/IPV6=yes/g" /etc/default/ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22 #ssh
sudo ufw allow 443 #https
sudo ufw allow 80 #http

sudo ufw enable
