#!/usr/bin/env bash
#Says who are you
#https://unix.stackexchange.com/questions/260735/how-to-use-sudo-u-option
#https://stackoverflow.com/questions/1988249/how-do-i-use-su-to-execute-the-rest-of-the-bash-script-as-that-user
sudo -u "$1" whoami
